### ISSUE TITLE
不是很熟python 这个错是啥 ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by a546109781** [Variante/AutoCatPlanet#1]
RT 运行AutoCatPlanet.py报这个 搜了半天百度也没整明白 是我要配置什么嘛

**Comment by Variante** [comment]
需要克隆一整个项目，不能只下一个文件

**Comment by a546109781** [comment]
![image](https://user-images.githubusercontent.com/7327840/184541324-6a757143-e626-474e-89c2-533bb0fbc3a5.png)
我是下载了整个项目

**Comment by Variante** [comment]
看起来是python没有使用当前这个目录作为环境变量，util就是那个util.py。试一下不用管理员的控制台看看？
当然也可以把
`from util import *`
换成
`from .util import *`
以及现在用的py是什么版本的呢？推荐3.6及以上.

**Comment by a546109781** [comment]
我卸载后重新安装了python（最新版）并且自定义安装，勾选了所有选项后可以了，可能是之前安装的时候是默认选项的原因
另外依赖还需要pip install scipy
感谢耐心解答
