### ISSUE TITLE
有时会出现抛竿时始终不会确认抛竿导致几分钟一直停留在抛竿页面，其他功能完全正常

### ISSUE THREAD

**Issue by BH2VSQ** [Variante/AutoCatPlanet#2]
有时会出现抛竿时始终不会确认抛竿导致几分钟一直停留在抛竿页面，其他功能完全正常

**Comment by Variante** [comment]
感觉是帧率低导致的，一直找不到合适的抛竿时机，你如果不在意完美抛竿可以把config里data中抛竿的mode改成3。

**Comment by Variante** [comment]
也有可能是没检测到抛竿页面，如果需要确认请把插件页面发一下

**Comment by BH2VSQ** [comment]
> 感觉是帧率低导致的，一直找不到合适的抛竿时机，你如果不在意完美抛竿可以把config里data中抛竿的mode改成3。

ok我试试

**Comment by BH2VSQ** [comment]
改mode为3之后那个判定圈刚出来他就触发点击了，非常快（？

**Comment by Variante** [comment]
> 改mode为3之后那个判定圈刚出来他就触发点击了，非常快（？

是符合预期的
