### ISSUE TITLE
为啥不动。。

### ISSUE THREAD

**Issue by a546109781** [Variante/AutoCatPlanet#3]
![image](https://user-images.githubusercontent.com/7327840/189096559-c409ab15-80bb-4681-9f39-4ad3e71eb677.png)
感觉是控制模拟器操作有问题？我手动钓了下，进行步骤的时候都打勾了
但是一动不动，也没报错

**Comment by BH2VSQ** [comment]
手动点一下抛竿试试

**Comment by BH2VSQ** [comment]
实在不行就重开程序

**Comment by a546109781** [comment]
> 手动点一下抛竿试试



> 实在不行就重开程序

都试过了 甚至换了别的模拟器都是一样
能识别到 就是不自动

**Comment by BH2VSQ** [comment]
> > 手动点一下抛竿试试
> 
> > 实在不行就重开程序
> 
> 都试过了 甚至换了别的模拟器都是一样 能识别到 就是不自动

那就不知道了（

**Comment by Variante** [comment]
使用adb shell getevent开始监听事件，然后手动点几下屏幕看看设备的id是什么，然后修改adb_device。
`/dev/input/event7: 0001 014a 00000001`
比如如果屏幕输出了这个那么应该改为/dev/input/event7

**Comment by a546109781** [comment]
> 使用adb shell getevent开始监听事件，然后手动点几下屏幕看看设备的id是什么，然后修改adb_device。 `/dev/input/event7: 0001 014a 00000001` 比如如果屏幕输出了这个那么应该改为/dev/input/event7

谢谢！正常了
